# Generated by Django 4.2.19 on 2025-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
